LOCAL_PATH := $(call my-dir)

ROOT_DIR   := $(LOCAL_PATH)/../../..
CORE_DIR   := $(ROOT_DIR)/platforms/libretro
SOURCE_DIR := $(ROOT_DIR)/src
INCLUDES   := -I$(CORE_DIR) -I$(SOURCE_DIR) -I$(ROOT_DIR)/third_party/clk

include $(CORE_DIR)/Makefile.common

COREFLAGS := -DHAVE_STDINT_H -DHAVE_INTTYPES_H $(INCLUDES) \
    -D__LIBRETRO__ -DGEARSF7000_PRODUCT_SC3000=1 \
    -DGEARSF7000_ENABLE_DEBUG_TOOLS=0 -DGEARSF7000_ENABLE_RECORDER=0 \
    -DGEARSF7000_ENABLE_MCP=0 -DGEARSF7000_ENABLE_AY=0 \
    -DGEARSF7000_ENABLE_SF7000=0 -DGEARSF7000_ENABLE_SR1000=0 \
    -DGEARSF7000_ENABLE_SP400=0 -DGEARSF7000_ENABLE_SDL_INPUT=0 \
    -DGEARSF7000_DISABLE_DISASSEMBLER -DGC_AUDIO_SAMPLE_RATE=48000

include $(CLEAR_VARS)
LOCAL_MODULE    := retro
LOCAL_SRC_FILES := $(SOURCES_CXX) $(SOURCES_C)
LOCAL_CFLAGS    := $(COREFLAGS)
LOCAL_CXXFLAGS  := $(COREFLAGS) -std=c++20
LOCAL_LDFLAGS   := -Wl,-version-script=$(CORE_DIR)/link.T
LOCAL_LDLIBS 	:= -llog
include $(BUILD_SHARED_LIBRARY)
