/* GearSC3000 libretro core options, adapted from current Gearsystem. */
#ifndef GEARSC3000_LIBRETRO_CORE_OPTIONS_H
#define GEARSC3000_LIBRETRO_CORE_OPTIONS_H

#include "libretro.h"

static struct retro_core_option_v2_category gearsc3000_option_categories[] = {
    { "system", "System", "Configure SC-3000 region and refresh timing." },
    { "video", "Video", "Configure the visible frame and presentation." },
    { "input", "Input", "Configure joystick input behaviour." },
    { NULL, NULL, NULL }
};

static struct retro_core_option_v2_definition gearsc3000_option_definitions[] = {
    {
        "gearsc3000_timing", "System > Refresh Rate (restart)", "Refresh Rate (restart)",
        "Choose the emulated video standard. Auto uses cartridge metadata. Timing follows the exact VDP clock.", NULL, "system",
        { { "Auto", NULL }, { "NTSC", "NTSC (~59.923 Hz)" },
          { "PAL", "PAL (~50.159 Hz)" }, { NULL, NULL } },
        "Auto"
    },
    {
        "gearsc3000_aspect_ratio", "Video > Aspect Ratio", "Aspect Ratio",
        "Choose the aspect ratio reported to the libretro frontend.", NULL, "video",
        { { "1:1 PAR", NULL }, { "4:3 DAR", NULL }, { "16:9 DAR", NULL }, { NULL, NULL } },
        "1:1 PAR"
    },
    {
        "gearsc3000_overscan", "Video > Borders", "Borders",
        "Include the SC-3000 border generated by the emulated TMS9918/9929. Output is 272x224 NTSC or 272x256 PAL.", NULL, "video",
        { { "Disabled", NULL }, { "Borders", "Enabled (272 pixels wide)" },
          { NULL, NULL } },
        "Disabled"
    },
    {
        "gearsc3000_up_down_allowed", "Input > Allow Opposing Directions", "Allow Opposing Directions",
        "Allow Up+Down and Left+Right to be pressed at the same time.", NULL, "input",
        { { "Disabled", NULL }, { "Enabled", NULL }, { NULL, NULL } },
        "Disabled"
    },
    { NULL, NULL, NULL, NULL, NULL, NULL, { { NULL, NULL } }, NULL }
};

static struct retro_core_options_v2 gearsc3000_options = {
    gearsc3000_option_categories,
    gearsc3000_option_definitions
};

static inline void gearsc3000_set_core_options(retro_environment_t environ_cb)
{
    unsigned version = 0;
    if (environ_cb(RETRO_ENVIRONMENT_GET_CORE_OPTIONS_VERSION, &version) && version >= 2)
    {
        environ_cb(RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2, &gearsc3000_options);
        return;
    }

    static const struct retro_variable variables[] = {
        { "gearsc3000_timing", "Refresh Rate (restart); Auto|NTSC|PAL" },
        { "gearsc3000_aspect_ratio", "Aspect Ratio; 1:1 PAR|4:3 DAR|16:9 DAR" },
        { "gearsc3000_overscan", "Borders; Disabled|Borders" },
        { "gearsc3000_up_down_allowed", "Allow Opposing Directions; Disabled|Enabled" },
        { NULL, NULL }
    };
    environ_cb(RETRO_ENVIRONMENT_SET_VARIABLES, (void*)variables);
}

#endif
