#ifndef GEARSF7000_WINDOWS_RESOURCE_H
#define GEARSF7000_WINDOWS_RESOURCE_H

#define IDR_SC3000_KEYBOARD_PNG       101
#define IDR_MEMORY_CONDENSED_TTF      102
#define IDR_MEMORY_CONDENSED_LIGHT_TTF 103

#endif
