/*
 * GearSF7000 - common debugger event stream
 *
 * Rules are configured outside the emulation hot path. Event capture is a
 * fixed-size ring buffer so tracing cannot allocate or grow while emulating.
 */

#ifndef DEBUG_EVENTS_H
#define DEBUG_EVENTS_H

#include "definitions.h"
#include <array>
#include <string>
#include <vector>

enum class DebugEventCategory : u8
{
    CpuExecute,
    CpuMemory,
    Vram,
    Io,
    VdpRegister,
    Fdc,
    Ppi,
    VideoTiming,
    Tape,
    Audio,
    // AY-3-8910 / YM2149 on the SGM-style expansion. Kept separate from Audio,
    // which means the SN76489: a rule that wants one almost never wants both,
    // and the register numbering is entirely different.
    AyExpansion,
    DeviceState
};

// Version 2 identifies devices and spaces by small runtime handles.  Stable
// string keys live in the descriptors, so the reusable rule engine does not
// need an enum containing every chip supported by every emulator.
typedef u16 DebugDeviceId;
typedef u16 DebugSpaceId;

namespace DebugCommonSpace
{
    static const DebugSpaceId Unknown   = 0;
    static const DebugSpaceId Execute   = 1;
    static const DebugSpaceId Memory    = 2;
    static const DebugSpaceId IoPorts   = 3;
    static const DebugSpaceId Registers = 4;
    static const DebugSpaceId State     = 5;
    static const DebugSpaceId Signals   = 6;
    static const DebugSpaceId Raster    = 7;
    // Emulator-specific spaces may use IDs from this value upward. Their
    // stable descriptor key, not the numeric ID, is persisted or sent by MCP.
    static const DebugSpaceId CustomFirst = 0x0100;
}

enum class DebugEventSource : u8
{
    Unknown = 0,
    LegacyHook,
    CpuInstruction,
    Reset,
    AutoIncrement,
    DeviceInternal,
    GuiDebugger,
    Mcp
};

enum class DebugEventPhase : u8
{
    Unknown = 0,
    BeforeCommit,
    AfterCommitInstructionBoundary,
    AfterCommitDeviceBoundary
};

enum DebugEventAccess : u8
{
    DebugEventAccess_None    = 0,
    DebugEventAccess_Read    = 1 << 0,
    DebugEventAccess_Write   = 1 << 1,
    DebugEventAccess_Execute = 1 << 2,
    // State transition generated by a device, rather than a CPU bus access.
    DebugEventAccess_Event   = 1 << 3
};

enum DebugEventAction : u8
{
    DebugEventAction_None  = 0,
    DebugEventAction_Log   = 1 << 0,
    DebugEventAction_Pause = 1 << 1
};

// Conditions are deliberately explicit instead of accepting expressions in
// the emulation path.  The legacy value/mask condition maps to
// AfterMaskedEqual, preserving existing GUI and MCP rules.
enum class DebugValueCondition : u8
{
    Any,
    AfterMaskedEqual,
    BeforeMaskedEqual,
    BeforeAndAfterMaskedEqual,
    BeforeNotEqualAfter,
    AfterLessThanBefore,
    AfterLessOrEqualBefore,
    AfterGreaterThanBefore,
    AfterGreaterOrEqualBefore,
    MaskedBitsChanged,
    BeforeMaskedSet,
    AfterMaskedSet,
    BeforeMaskedClear,
    AfterMaskedClear
};

// Describes what the emulation engine can actually publish for a category.
// GUI and remote adapters use the same table so they cannot offer rules that
// can never match the corresponding core hook.
struct DebugEventCategoryCapabilities
{
    u32 targetMax = 0xFFFF;
    u8 supportedAccesses = DebugEventAccess_None;
    u8 beforeValueAccesses = DebugEventAccess_None;
    u8 afterValueAccesses = DebugEventAccess_None;
};

enum DebugDescriptorCapability : u8
{
    DebugDescriptorCapability_None             = 0,
    DebugDescriptorCapability_EventsPublished  = 1 << 0,
    DebugDescriptorCapability_SnapshotReadable = 1 << 1,
    DebugDescriptorCapability_Mutable           = 1 << 2
};

struct DebugTargetDescriptor
{
    u32 id;
    const char* name;
    u8 bitWidth;
};

struct DebugSpaceDescriptor
{
    DebugSpaceId id;
    const char* key;
    const char* name;
    u32 targetMin;
    u32 targetMax;
    u8 supportedAccesses;
    u8 beforeValueAccesses;
    u8 afterValueAccesses;
    u8 defaultBitWidth;
    u8 capabilities;
    const DebugTargetDescriptor* targets;
    size_t targetCount;
};

struct DebugDeviceDescriptor
{
    DebugDeviceId id;
    DebugDeviceId parentId;
    // Stable instance path (for rules/configuration) and reusable hardware
    // type (for decoders shared by different machines or multiple instances).
    const char* key;
    const char* typeKey;
    const char* displayName;
    const DebugSpaceDescriptor* spaces;
    size_t spaceCount;
};

struct DebugProbe
{
    DebugDeviceId device = 0;
    DebugSpaceId space = DebugCommonSpace::Unknown;
    u32 target = 0;
};

// Non-owning registry: descriptors are normally static data supplied by the
// emulator at startup.  Another emulator can instantiate the same class with
// a completely different catalog without changing DebugEventManager.
class DebugDeviceRegistry
{
public:
    DebugDeviceRegistry(const DebugDeviceDescriptor* devices = NULL, size_t count = 0);
    void SetCatalog(const DebugDeviceDescriptor* devices, size_t count);
    const DebugDeviceDescriptor* GetDevices(size_t* count = NULL) const;
    const DebugDeviceDescriptor* FindDevice(DebugDeviceId device) const;
    const DebugDeviceDescriptor* FindDevice(const char* stableKey) const;
    const DebugDeviceDescriptor* GetParent(DebugDeviceId device) const;
    size_t GetChildCount(DebugDeviceId parent) const;
    const DebugDeviceDescriptor* GetChild(DebugDeviceId parent, size_t index) const;
    const DebugSpaceDescriptor* FindSpace(DebugDeviceId device, DebugSpaceId space) const;
    const DebugSpaceDescriptor* FindSpace(DebugDeviceId device, const char* stableKey) const;

private:
    const DebugDeviceDescriptor* m_devices;
    size_t m_count;
};

struct DebugRule
{
    u32 id = 0;
    bool enabled = true;
    std::string name;
    std::string description;
    DebugEventCategory category = DebugEventCategory::CpuMemory;
    u32 addressStart = 0;
    u32 addressEnd = 0;
    u8 accessMask = DebugEventAccess_None;
    bool useValueCondition = false;
    u64 valueMask = 0xFF;
    u64 valueExpected = 0;
    u64 beforeValueExpected = 0;
    DebugValueCondition valueCondition = DebugValueCondition::Any;
    u64 breakOnHit = 1;       // 1 = first match; 0 = never pause by hit count
    u64 hitCount = 0;
    bool oneShot = false;
    u8 actions = DebugEventAction_Log | DebugEventAction_Pause;

    // Native device-space rule. Stable keys are retained for MCP/config;
    // runtime handles are resolved once when the rule is added.
    bool useProbe = false;
    DebugDeviceId device = 0;
    DebugSpaceId space = DebugCommonSpace::Unknown;
    std::string deviceKey;
    std::string spaceKey;
};

// Device-neutral raster classification. A VDP maps its own vertical and
// horizontal region enums onto these few buckets, which are what a person
// reading a trace actually wants to distinguish.
enum class DebugRasterRegion : u8
{
    Unknown = 0,
    ActiveDisplay,
    Border,
    Blanking,
    Sync
};

// Which VRAM slot calendar the VDP was arbitrating with. This is what decides
// how much CPU bandwidth the port had, so it belongs beside the raster
// position rather than being re-derived from mode registers after the fact.
enum class DebugVdpSlotCalendar : u8
{
    Unknown = 0,
    // Display off or outside the active lines: nearly every slot is the CPU's.
    Refresh,
    Graphics,
    Text,
    Multicolor
};

// Where a device-internal event happened on the raster, and how long the CPU
// left between this port access and the previous one. A device publishes it
// only when it actually knows both; the CPU bus path leaves it empty.
struct DebugEventRasterContext
{
    bool rasterKnown = false;
    u16 line = 0;
    // Horizontal position in TMS9918 dots (0..341), not framebuffer pixels:
    // it stays meaningful in blanking, where there is no pixel to name.
    u16 dot = 0;
    DebugRasterRegion verticalRegion = DebugRasterRegion::Unknown;
    DebugRasterRegion horizontalRegion = DebugRasterRegion::Unknown;
    DebugVdpSlotCalendar calendar = DebugVdpSlotCalendar::Unknown;
    bool gapKnown = false;
    // T-states between the previous CPU port access and this one, measured
    // end-of-transfer to end-of-transfer because that is when the VDP latches.
    u32 tStatesSincePreviousAccess = 0;
};

const char* GetDebugRasterRegionName(DebugRasterRegion region);
const char* GetDebugVdpSlotCalendarName(DebugVdpSlotCalendar calendar);

struct DebugEvent
{
    static const u8 SchemaVersion = 2;

    u64 sequence = 0;
    u64 clock = 0;
    u32 ruleId = 0;           // 0 means a legacy breakpoint/event
    u16 pc = 0;
    u16 target = 0;
    // `value`/`valueKnown` remain ABI-compatible aliases of afterValue for
    // MCP clients built before the Before/After trace format.
    u8 value = 0;
    u8 beforeValue = 0;
    u8 afterValue = 0;
    u8 category = 0;
    u8 access = DebugEventAccess_None;
    u8 actions = DebugEventAction_None;
    bool valueKnown = false;
    bool beforeKnown = false;
    bool afterKnown = false;

    // Device-aware v2 view.  The v1 fields above remain populated so older
    // GUI and MCP clients keep working during the migration.
    u8 schemaVersion = SchemaVersion;
    DebugDeviceId device = 0;
    DebugSpaceId space = DebugCommonSpace::Unknown;
    DebugEventSource source = DebugEventSource::Unknown;
    DebugEventPhase phase = DebugEventPhase::Unknown;
    u8 valueWidth = 8;
    u32 targetV2 = 0;
    u64 beforeValueV2 = 0;
    u64 afterValueV2 = 0;

    // Empty unless the publishing device supplied it. Kept as a plain member
    // rather than a schema bump: older readers ignore it, and its `known`
    // flags already say when there is nothing to show.
    DebugEventRasterContext raster;

    // Which physical page `pc` was in. $8000-$BFFF means different code
    // depending on the mapper bank, so a logical address on its own cannot
    // identify a routine - and now that the bank is saved and rewound with
    // everything else, attributing code to the wrong page is an easy mistake
    // to make and a hard one to see.
    bool bankKnown = false;
    u8 bank = 0;
};

DebugEventCategoryCapabilities GetDebugEventCategoryCapabilities(DebugEventCategory category);
DebugProbe AdaptLegacyDebugProbe(DebugEventCategory category, u8 access, u16 target);
// GearSF7000 bus decoder. IOPorts implementations in other emulators provide
// their own decoder and can still use DebugEventManager unchanged.
DebugProbe DecodeGearIoPort(u16 rawPort);
DebugProbe GetGearVdpStateProbe(u32 target);
const DebugDeviceRegistry& GetGearDebugDeviceRegistry();
const DebugDeviceDescriptor* FindDebugDeviceDescriptor(DebugDeviceId device);
const DebugSpaceDescriptor* FindDebugSpaceDescriptor(DebugDeviceId device, DebugSpaceId space);
const char* GetDebugDeviceName(DebugDeviceId device);
const char* GetDebugSpaceName(DebugSpaceId space);
const char* GetDebugEventSourceName(DebugEventSource source);
const char* GetDebugEventPhaseName(DebugEventPhase phase);
bool DebugValueConditionNeedsBefore(DebugValueCondition condition);
bool DebugValueConditionNeedsAfter(DebugValueCondition condition);
// Returns NULL when valid, otherwise a stable human-readable reason.
const char* ValidateDebugRule(const DebugRule& rule);
const char* ValidateDebugRule(const DebugRule& rule, const DebugDeviceRegistry& registry);

class DebugEventManager
{
public:
    // Default depth. Enough for rules, which are selective by nature - a
    // handful of interesting moments. Tracing is the same machinery with the
    // filters removed, and then it is not nearly enough: an SC-3000 executes
    // roughly sixty thousand instructions a frame, so an unfiltered CpuExecute
    // rule would cycle this ring fifteen times per frame. Hence
    // SetEventCapacity().
    static const size_t DefaultEventCapacity = 4096;

    explicit DebugEventManager(const DebugDeviceRegistry* registry = NULL);

    u32 AddRule(const DebugRule& rule);
    bool RemoveRule(u32 id);
    void ClearRules();
    std::vector<DebugRule>& GetRules();
    const std::vector<DebugRule>& GetRules() const;

    // Returns true only when a matching rule requests an emulation pause.
    bool Evaluate(DebugEventCategory category, u8 access, u16 target,
                  u8 value, bool valueKnown, u16 pc, u64 clock);
    // raster is optional and passed by devices that know where the beam was.
    // For anything the VDP publishes it is the difference between "a write to
    // $1B00 happened" and "a write to $1B00 happened on line 96 at dot 208",
    // which is the whole point of tracing on this machine.
    bool Evaluate(DebugEventCategory category, u8 access, u16 target,
                  u8 beforeValue, bool beforeKnown, u8 afterValue, bool afterKnown,
                  u16 pc, u64 clock,
                  const DebugEventRasterContext* raster = NULL);
    // Publishes one CPU bus operation. The decoded probe qualifies the same
    // access for device-port rules (currently the legacy PPI Ports view)
    // without requiring a second hook inside the device implementation.
    bool EvaluateIoPort(const DebugProbe& decodedProbe, u16 rawPort, u8 access,
                        u8 value, bool valueKnown, u16 pc, u64 clock);
    bool EvaluateProbe(const DebugProbe& probe, u8 access,
                       u64 beforeValue, bool beforeKnown,
                       u64 afterValue, bool afterKnown,
                       DebugEventSource source, DebugEventPhase phase,
                       u16 pc, u64 clock,
                       const DebugEventRasterContext* raster = NULL);

    // Adapts existing CPU/memory breakpoints to the new event stream.
    void RecordLegacyHit(DebugEventCategory category, u8 access, u16 target,
                         u8 value, bool valueKnown, u16 pc, u64 clock);

    // Resizing clears: a ring holding events indexed against the old depth
    // cannot be reinterpreted against a new one. Returns the capacity that was
    // actually applied, which is clamped.
    // Asked for the physical page only when an event is actually recorded, so
    // an unmatched rule costs nothing. The manager cannot work it out itself:
    // the authoritative bank lives in the mapper, which it does not know about.
    typedef u8 (*BankProvider)(void* context);
    void SetBankProvider(BankProvider provider, void* context);

    size_t SetEventCapacity(size_t capacity);
    size_t GetEventCapacity() const;

    void ClearEvents();
    size_t GetEventCount() const;
    u64 GetDroppedEventCount() const;
    void CopyEvents(std::vector<DebugEvent>& out) const;

private:
    bool RuleMatchesValue(const DebugRule& rule, u64 beforeValue, bool beforeKnown,
                          u64 afterValue, bool afterKnown) const;
    bool EvaluateWithProbe(DebugEventCategory category, u8 access, u16 target,
                           u64 beforeValue, bool beforeKnown,
                           u64 afterValue, bool afterKnown, u16 pc, u64 clock,
                           const DebugProbe* probeOverride,
                           DebugEventSource source = DebugEventSource::Unknown,
                           DebugEventPhase phase = DebugEventPhase::Unknown,
                           const DebugEventRasterContext* raster = NULL);
    void PushEvent(u32 ruleId, DebugEventCategory category, u8 access,
                  u16 target, u8 value, bool valueKnown, u16 pc, u64 clock,
                  u8 actions);
    void PushEvent(u32 ruleId, DebugEventCategory category, u8 access,
                   u16 target, u8 beforeValue, bool beforeKnown,
                   u8 afterValue, bool afterKnown, u16 pc, u64 clock,
                   u8 actions);
    void PushEventWithProbe(u32 ruleId, DebugEventCategory category, u8 access,
                            u16 target, u8 beforeValue, bool beforeKnown,
                            u8 afterValue, bool afterKnown, u16 pc, u64 clock,
                            u8 actions, const DebugProbe& probe);
    void PushEventWithProbe(u32 ruleId, DebugEventCategory category, u8 access,
                            u16 target, u64 beforeValue, bool beforeKnown,
                            u64 afterValue, bool afterKnown, u16 pc, u64 clock,
                            u8 actions, const DebugProbe& probe,
                            DebugEventSource source, DebugEventPhase phase,
                            const DebugEventRasterContext* raster = NULL);

private:
    std::vector<DebugRule> m_rules;
    // A vector rather than an array because the depth is chosen at runtime.
    std::vector<DebugEvent> m_events;
    size_t m_eventHead;
    size_t m_eventCount;
    u64 m_nextRuleId;
    u64 m_nextSequence;
    u64 m_droppedEvents;
    const DebugDeviceRegistry* m_registry;
    BankProvider m_bankProvider;
    void* m_bankContext;
};

#endif /* DEBUG_EVENTS_H */
